name: pblocker
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - requests
      - beautifulsoup4
      - pygetwindow
      - psutil
      - plyer
      - transformers
      - torch
      - scapy
      - websockets
      - notification